name: Delegate Uprising
favicon: null
layout_spectrum: 0.24413
typography_spectrum: 0.78168
title: 'Delegate Uprising: The Best Way to Stop a Bullet is to Tell a Story'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03060f'
    - '#fafeff'
    - '#90c2fd'
    - '#192f78'
    - '#3f7de2'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
